### PR TITLE
Update Games List.json

### PR DESCRIPTION
**Pull request by ckacadv**
added Battlefield 3, Saints Row: The Third and Pure

i dont know how to use this thing

### CODE REVIEW

**Comment by MrCoolAndroid** [comment]
There are plenty of syntax errors, I will try to fix them later

**Comment by MrCoolAndroid** [comment]
I was able to check some stuff and I can't directly edit the syntax errors, can you try fix them? Because you half deleted a game (XDefiant), also check your Saints Row image, it is not 1024x1024

**Comment by ckacadv** [comment]
i fixed Saints Row image and i added back XDefiant. What else should i do?

**Comment by MrCoolAndroid** [comment]
Saints Row titleicon is still not on 1024x1024, I can look for one if you want

**Pull request merged**
