### PR TITLE
Update Games List.json

### PR DESCRIPTION
**Pull request by ComixGaming248**
New pull requst: had to rewrite some code and had too many commits. I applied your suggestions.

(https://assets-prd.ignimgs.com/2022/04/22/raskulls-1650586617976.jpg?width=1024)

([https://xbox360media.ign.com/xbox360/image/object/850/850005/XBL_Carcassonne.jpg?width=250&crop=1%3A1%2Csmart&auto=webp)`](https://xbox360media.ign.com/xbox360/image/object/850/850005/XBL_Carcassonne.jpg?width=250&crop=1%3A1%2Csmart&auto=webp)%60)

I commited these changes to my fork, thanks for the feedback. Also I didn't really know what to put for `titlebackround` so I just didn't put anything so as to not interfere.
The new image for Carcassone is a 219x219 square, the new image for Raskulls is 1024x1024.

### CODE REVIEW

**Review by MrCoolAndroid — CHANGES_REQUESTED** [review]
`titlebackground` is mandatory on all games, if you want I can try and see if I can find any for those games

**Comment by ComixGaming248** [comment]
That would be be great thanks. I'll keep looking too.

**Review by MrCoolAndroid — APPROVED** [review]
I fixed typos, missing backgrounds and icons and reverted Minecraft: Xbox 360 Edition changes

**Comment by ComixGaming248** [comment]
Thanks for the help bro, I appreciate it.

**Review by MrCoolAndroid — APPROVED** [review]

**Pull request merged**
