### PR TITLE
Update Games List.json

### PR DESCRIPTION
**Pull request by Kaerix**
Added Call of Duty 4: Modern Warfare
Changed name to "Call of Duty: Advanced Warfare" from "COD: Advanced Warfare"
Changed name to "Call of Duty: Black Ops II" from "COD: Black Ops II"
Changed name to "Call of Duty: Black Ops III" from "COD: Black Ops III"

### CODE REVIEW

**Comment by MrCoolAndroid** [comment]
I'm gonna merge it, but just in case check if it shows the image, if it doesn't make a new pull request

**Comment by Kaerix** [comment]
image
It only shows this.

**Comment by MrCoolAndroid** [comment]
I figured, looks like the name is only Modern Warfare, is there someone that can check for you if it shows the same name on a console?

**Comment by Kaerix** [comment]
No, it shows Call of Duty 4

**Comment by MrCoolAndroid** [comment]
I'm gonna change it to "Call of Duty 4: Modern Warfare" and see what happens

**Comment by Kaerix** [comment]
Still the same, maybe changing the image to this link: 
https://tinypic.host/images/2022/09/29/59b109c700b500daa9ef3a6769bc8c6f-1.png
would fix it?

**Comment by MrCoolAndroid** [comment]
I see you joined the Discord, wanna take it there?

**Comment by Kaerix** [comment]
Yeah sure

**Pull request merged**
